---
daylily:
  git_ephemeral_cluster_repo_tag: 2.2.6
  git_ephemeral_cluster_repo_release_tag: 2.2.6
  git_ephemeral_cluster_repo: https://github.com/lsmc-bio/daylily-ephemeral-cluster.git
  analysis_root: /fsx/analysis_results/
  sentieon_lic_path: /fsx/data/cached_envs/x.lic
  sentieon_tmpdir: /dev/shm/
  sentieon_install_dir: /fsx/data/cached_envs/sentieon-genomics-202503.01.rc1/
